import { useEffect, useState } from 'react';
import type { FormEvent, ReactNode } from 'react';
import api, { refreshAssetQuote, refreshAssetReferenceValuation } from '../api';
import { AlertMessage, EmptyTableRow } from '../components/Feedback';
import { PageHeader } from '../components/PageHeader';
import { Pagination } from '../components/Pagination';
import { Badge, Icon } from '../components/Visual';
import { ReferenceValuationCell, ReferenceValuationDetails } from '../components/ReferenceValuation';
import type { MarketQuote } from '../types/market-data';
import type { PageResult } from '../types/pagination';
import type { ReferenceValuationResponse } from '../types/reference-valuation';
import { getErrorMessage } from '../utils/error';
import { formatCurrency } from '../utils/format';
import { extractMarketQuote, formatQuoteTime, formatReferenceQuote, isMarketQuoteSupported, marketQuoteRefreshMessage, marketQuoteRefreshWarning, quoteFreshnessLabel, updateAssetMarketQuote } from '../utils/marketQuote';
import { isReferenceValuationSupported, referenceValuationRefreshMessage, updateAssetReferenceValuation } from '../utils/referenceValuation';

interface Asset { id: number; name: string; symbol: string; type: string; market: string; currency: string; quantity: number; avgCost: number; currentPrice: number; marketValue: number; profitLoss: number; profitLossRate: number; createdAt: string; marketQuote?: MarketQuote | null; referenceValuation?: ReferenceValuationResponse | null; }
const pageSize = 20;

export default function Assets() {
    const [assets, setAssets] = useState<Asset[]>([]); const [total, setTotal] = useState(0); const [page, setPage] = useState(1); const [showForm, setShowForm] = useState(false); const [selectedAsset, setSelectedAsset] = useState<Asset | null>(null);
    const [form, setForm] = useState({ name: '', symbol: '', type: 'STOCK', market: '', currency: 'CNY', quantity: 0, avgCost: 0 }); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [warning, setWarning] = useState(''); const [refreshingAssetIds, setRefreshingAssetIds] = useState<Set<number>>(new Set()); const [refreshingReferenceValuationIds, setRefreshingReferenceValuationIds] = useState<Set<number>>(new Set());
    const fetch = async (targetPage = page) => { const res = await api.get('/assets/page', { params: { page: targetPage, size: pageSize } }); const data: PageResult<Asset> = res.data.data; const records = data.records || []; if (records.length === 0 && targetPage > 1 && (data.total || 0) > 0) { await fetch(targetPage - 1); return; } setAssets(records); setTotal(data.total || 0); setPage(data.page || targetPage); };
    useEffect(() => { fetch(1).catch(err => setError(getErrorMessage(err, '资产列表加载失败'))); // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);
    const create = async (event: FormEvent) => { event.preventDefault(); setError(''); setSuccess(''); try { await api.post('/assets', form); setShowForm(false); setSuccess('资产已创建'); await fetch(page); } catch (err) { setError(getErrorMessage(err, '资产保存失败')); } };
    const showDetail = async (id: number) => { setError(''); setSuccess(''); try { const res = await api.get(`/assets/${id}`); setSelectedAsset(res.data.data); } catch (err) { setError(getErrorMessage(err, '资产详情加载失败')); } };
    const updatePrice = async (id: number) => { const price = prompt('输入当前价格:'); if (!price) return; setError(''); setSuccess(''); try { await api.put(`/assets/${id}/price?price=${price}`); setSuccess('资产价格已更新'); await fetch(page); if (selectedAsset?.id === id) await showDetail(id); } catch (err) { setError(getErrorMessage(err, '资产价格更新失败')); } };
    const closeAsset = async (asset: Asset) => { if (!confirm('确认将该资产标记为已清仓？此操作不会计算卖出收益。')) return; setError(''); setSuccess(''); try { const res = await api.put(`/assets/${asset.id}/close`); setSuccess('资产已清仓'); await fetch(page); if (selectedAsset?.id === asset.id) setSelectedAsset(res.data.data); } catch (err) { setError(getErrorMessage(err, '资产清仓失败')); } };
    const remove = async (asset: Asset) => { if (!confirm(`确定删除资产“${asset.name}”吗？`)) return; setError(''); setSuccess(''); try { await api.delete(`/assets/${asset.id}`); const nextPage = assets.length === 1 && page > 1 ? page - 1 : page; if (selectedAsset?.id === asset.id) setSelectedAsset(null); setSuccess('资产已删除'); await fetch(nextPage); } catch (err) { setError(getErrorMessage(err, '资产删除失败')); } };
    const refreshQuote = async (asset: Asset) => { setError(''); setSuccess(''); setWarning(''); setRefreshingAssetIds(ids => new Set(ids).add(asset.id)); try { const response = await refreshAssetQuote(asset.id); const marketQuote = extractMarketQuote(response); setAssets(current => updateAssetMarketQuote(current, asset.id, marketQuote)); setSelectedAsset(current => current?.id === asset.id ? { ...current, marketQuote } : current); const nextWarning = marketQuoteRefreshWarning(response); if (nextWarning) setWarning(nextWarning); else setSuccess('参考行情已更新'); } catch (err) { setError(marketQuoteRefreshMessage(err)); } finally { setRefreshingAssetIds(ids => { const next = new Set(ids); next.delete(asset.id); return next; }); } };
    const refreshReferenceValuation = async (asset: Asset) => { setError(''); setSuccess(''); setWarning(''); setRefreshingReferenceValuationIds(ids => new Set(ids).add(asset.id)); try { const referenceValuation = await refreshAssetReferenceValuation(asset.id); setAssets(current => updateAssetReferenceValuation(current, asset.id, referenceValuation)); setSelectedAsset(current => current?.id === asset.id ? { ...current, referenceValuation } : current); setSuccess('市场参考估值已更新'); } catch (err) { setError(referenceValuationRefreshMessage(err)); } finally { setRefreshingReferenceValuationIds(ids => { const next = new Set(ids); next.delete(asset.id); return next; }); } };
    const hasPosition = (asset: Asset) => Number(asset.quantity) > 0; const totalPages = Math.max(1, Math.ceil(total / pageSize)); const hasNextPage = page < totalPages && assets.length >= pageSize;
    return <div>
        <PageHeader title="投资资产" subtitle="全面掌握持仓资产表现与盈亏概况" actions={<button type="button" className="button button--primary" onClick={() => setShowForm(!showForm)}>新增资产</button>} />
        {error && <AlertMessage type="error">{error}</AlertMessage>}{success && <AlertMessage type="success">{success}</AlertMessage>}{warning && <AlertMessage type="warning">{warning}</AlertMessage>}
        {showForm && <form onSubmit={create} className="page-panel"><h2 className="content-card__title">新增资产</h2><div className="form-grid"><Field label="名称"><input className="field__control" value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} required /></Field><Field label="代码"><input className="field__control" value={form.symbol} onChange={event => setForm({ ...form, symbol: event.target.value })} /></Field><Field label="数量"><input className="field__control" type="number" step="0.01" value={form.quantity} onChange={event => setForm({ ...form, quantity: +event.target.value })} required /></Field><Field label="平均成本"><input className="field__control" type="number" step="0.01" value={form.avgCost} onChange={event => setForm({ ...form, avgCost: +event.target.value })} required /></Field></div><button type="submit" className="button button--primary" style={{ marginTop: 16 }}>保存</button></form>}
        {selectedAsset && <section className="content-card"><div className="page-header"><h2 className="content-card__title">资产详情</h2><div className="page-header__actions">{hasPosition(selectedAsset) && <button type="button" className="button button--success button--small" onClick={() => closeAsset(selectedAsset)}>清仓</button>}<button type="button" className="button button--neutral button--small" onClick={() => setSelectedAsset(null)}>关闭</button></div></div><div className="detail-grid"><DetailItem label="名称" value={selectedAsset.name} /><DetailItem label="代码" value={selectedAsset.symbol || '-'} /><DetailItem label="类型" value={selectedAsset.type} /><DetailItem label="市场" value={selectedAsset.market || '-'} /><DetailItem label="币种" value={selectedAsset.currency || 'CNY'} /><DetailItem label="持仓数量" value={selectedAsset.quantity} /><DetailItem label="创建时间" value={selectedAsset.createdAt?.replace('T', ' ') || '-'} /></div><section className="reference-valuation"><h3 className="content-card__title">人工估值</h3><p className="table-secondary">用户确认的账务数据</p><div className="detail-grid"><DetailItem label="人工平均成本（CNY）" value={formatCurrency(selectedAsset.avgCost)} /><DetailItem label="人工当前价格（CNY）" value={selectedAsset.currentPrice ? formatCurrency(selectedAsset.currentPrice) : '-'} /><DetailItem label="人工市场价值（CNY）" value={formatCurrency(selectedAsset.marketValue)} /><DetailItem label="人工浮动盈亏" value={`${formatCurrency(selectedAsset.profitLoss)} (${selectedAsset.profitLossRate?.toFixed(2)}%)`} /></div></section>{isMarketQuoteSupported(selectedAsset) && <MarketQuoteDetails quote={selectedAsset.marketQuote} />}<ReferenceValuationDetails asset={selectedAsset} /></section>}
        <section className="content-card"><h2 className="content-card__title"><span className="content-card__title-icon"><Icon name="assets" size={17} /></span>持仓资产明细</h2><div className="table-scroll"><table className="data-table"><thead><tr><th>名称 / 代码</th><th>类型</th><th className="cell-number">持仓</th><th className="cell-number">人工平均成本（CNY）</th><th className="cell-number">人工当前价格（CNY）</th><th className="cell-number">人工市值（CNY）</th><th className="cell-number">人工盈亏</th><th>参考行情</th><th>市场参考估值</th><th>操作</th></tr></thead><tbody>{assets.map(asset => <tr key={asset.id}><td><span className="table-primary">{asset.name}</span><span className="table-secondary">{asset.symbol || '—'}</span></td><td><TypeBadge type={asset.type} /></td><td className="cell-number">{asset.quantity}</td><td className="cell-number">{formatCurrency(asset.avgCost)}</td><td className="cell-number">{asset.currentPrice ? formatCurrency(asset.currentPrice) : '-'}</td><td className="cell-number">{formatCurrency(asset.marketValue)}</td><td className="cell-number"><span className={`amount amount--${asset.profitLoss >= 0 ? 'positive' : 'negative'}`}>{formatCurrency(asset.profitLoss)} ({asset.profitLossRate?.toFixed(2)}%)</span></td><td>{isMarketQuoteSupported(asset) ? <MarketQuoteCell quote={asset.marketQuote} /> : '—'}</td><td><ReferenceValuationCell asset={asset} /></td><td className="cell-actions"><div className="data-table__actions"><button type="button" className="button button--secondary button--small" onClick={() => showDetail(asset.id)}>详情</button><button type="button" className="button button--neutral button--small" onClick={() => updatePrice(asset.id)}>更新价格</button>{isMarketQuoteSupported(asset) && <button type="button" className="button button--warning button--small" onClick={() => refreshQuote(asset)} disabled={refreshingAssetIds.has(asset.id)}>{refreshingAssetIds.has(asset.id) ? '刷新中…' : '刷新行情'}</button>}{isReferenceValuationSupported(asset) && <button type="button" className="button button--primary button--small" onClick={() => refreshReferenceValuation(asset)} disabled={refreshingReferenceValuationIds.has(asset.id)}>{refreshingReferenceValuationIds.has(asset.id) ? '刷新中…' : '刷新参考估值'}</button>}{hasPosition(asset) && <button type="button" className="button button--success button--small" onClick={() => closeAsset(asset)}>清仓</button>}<button type="button" className="button button--danger button--small" onClick={() => remove(asset)}>删除</button></div></td></tr>)}{assets.length === 0 && <EmptyTableRow colSpan={10} message="暂无资产" />}</tbody></table></div><Pagination page={page} totalPages={totalPages} summary={<>共 {total} 个资产</>} previousDisabled={page <= 1} nextDisabled={!hasNextPage} onPrevious={() => fetch(page - 1)} onNext={() => fetch(page + 1)} /></section>
    </div>;
}
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="field"><span className="field__label">{label}</span>{children}</label>; }
function DetailItem({ label, value }: { label: string; value: string | number }) { return <div className="detail-item"><div className="detail-item__label">{label}</div><div className="detail-item__value">{value}</div></div>; }
function TypeBadge({ type }: { type: string }) { const tone = type === 'STOCK' ? 'primary' : type === 'ETF' ? 'success' : type === 'FUND' ? 'warning' : 'primary'; return <Badge tone={tone}>{type}</Badge>; }
function MarketQuoteCell({ quote }: { quote: MarketQuote | null | undefined }) { return quote ? <div><div>{formatReferenceQuote(quote)}</div><span className={`table-secondary amount amount--${quote.freshness === 'FRESH' ? 'positive' : 'negative'}`}>状态：{quoteFreshnessLabel(quote)}</span></div> : <span className="table-secondary">尚未获取参考行情</span>; }
function MarketQuoteDetails({ quote }: { quote: MarketQuote | null | undefined }) { return quote ? <section style={{ marginTop: 20 }}><h3 className="content-card__title">参考行情（{quote.currency}）</h3><div className="detail-grid"><DetailItem label="参考行情" value={formatReferenceQuote(quote)} /><DetailItem label="新鲜度" value={quoteFreshnessLabel(quote)} /><DetailItem label="报价时间" value={formatQuoteTime(quote.quoteTime)} /><DetailItem label="获取时间" value={formatQuoteTime(quote.fetchedAt)} /><DetailItem label="来源" value={quote.provider || '-'} /></div></section> : <p className="table-secondary">尚未获取参考行情</p>; }
