import { useEffect, useMemo, useState } from 'react';
import type { FormEvent, ReactNode } from 'react';
import api from '../api';
import { AlertMessage, EmptyTableRow } from '../components/Feedback';
import { PageHeader } from '../components/PageHeader';
import { Pagination } from '../components/Pagination';
import { Badge, Icon } from '../components/Visual';
import type { PageResult } from '../types/pagination';
import { getErrorMessage } from '../utils/error';
import { formatTransactionAmount, formatTransactionType } from '../utils/format';

type TransactionType = 'INCOME' | 'EXPENSE' | 'ADJUSTMENT';
interface Transaction { id: number; accountId: number; categoryId: number; type: TransactionType; amount: number; currency: string; description?: string; transactedAt: string; }
interface Account { id: number; name: string; status: string; }
interface Category { id: number; name: string; type: string; }
interface TransactionForm { accountId: string; categoryId: string; type: TransactionType; amount: string; currency: string; description: string; transactedAt: string; }
interface Filters { type: string; accountId: string; categoryId: string; start: string; end: string; }
const pageSize = 20; const typeOptions: TransactionType[] = ['INCOME', 'EXPENSE', 'ADJUSTMENT'];
const emptyForm = (): TransactionForm => ({ accountId: '', categoryId: '', type: 'EXPENSE', amount: '', currency: 'CNY', description: '', transactedAt: toInputDateTime(new Date()) });
function toInputDateTime(value: string | Date) { const date = value instanceof Date ? value : new Date(value); if (Number.isNaN(date.getTime())) return ''; const pad = (num: number) => String(num).padStart(2, '0'); return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`; }
function toLocalDateTime(value: string) { return value.length === 16 ? `${value}:00` : value; }

export default function Transactions() {
    const [transactions, setTransactions] = useState<Transaction[]>([]); const [total, setTotal] = useState(0); const [page, setPage] = useState(1); const [accounts, setAccounts] = useState<Account[]>([]); const [categories, setCategories] = useState<Category[]>([]);
    const [showForm, setShowForm] = useState(false); const [editingId, setEditingId] = useState<number | null>(null); const [form, setForm] = useState<TransactionForm>(emptyForm); const [filters, setFilters] = useState<Filters>({ type: '', accountId: '', categoryId: '', start: '', end: '' }); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
    const accountNameById = useMemo(() => new Map(accounts.map(account => [account.id, account.name])), [accounts]); const categoryNameById = useMemo(() => new Map(categories.map(category => [category.id, category.name])), [categories]);
    const selectableCategories = useMemo(() => form.type === 'ADJUSTMENT' ? categories : categories.filter(category => category.type === form.type), [categories, form.type]);
    const fetchTransactions = async (targetPage = page) => { const params: Record<string, string | number> = { page: targetPage, size: pageSize }; if (filters.type) params.type = filters.type; if (filters.accountId) params.accountId = filters.accountId; if (filters.categoryId) params.categoryId = filters.categoryId; if (filters.start) params.start = toLocalDateTime(filters.start); if (filters.end) params.end = toLocalDateTime(filters.end); const res = await api.get('/transactions/page', { params }); const data: PageResult<Transaction> = res.data.data; setTransactions(data.records || []); setTotal(data.total || 0); setPage(data.page || targetPage); };
    const fetchOptions = async () => { const [accountRes, categoryRes] = await Promise.all([api.get('/accounts'), api.get('/categories')]); setAccounts(accountRes.data.data || []); setCategories(categoryRes.data.data || []); };
    useEffect(() => { fetchOptions().catch(err => setError(getErrorMessage(err, '操作失败，请稍后重试'))); fetchTransactions(1).catch(err => setError(getErrorMessage(err, '操作失败，请稍后重试'))); // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);
    const validate = () => { const amount = Number(form.amount); if (!form.accountId) return '请选择账户'; if (!form.categoryId) return '请选择分类'; if (!form.transactedAt) return '请选择交易时间'; if (!form.amount || Number.isNaN(amount)) return '请输入有效金额'; if ((form.type === 'INCOME' || form.type === 'EXPENSE') && amount <= 0) return '收入和支出金额必须大于 0'; if (form.type === 'ADJUSTMENT' && amount === 0) return '调整金额不能为 0'; if (form.type === 'ADJUSTMENT' && !form.description.trim()) return '调整流水必须填写说明'; return ''; };
    const resetForm = () => { setForm(emptyForm()); setEditingId(null); }; const openCreateForm = () => { resetForm(); setShowForm(true); setError(''); setSuccess(''); }; const closeForm = () => { resetForm(); setShowForm(false); };
    const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); setSuccess(''); const validationError = validate(); if (validationError) { setError(validationError); return; } const payload = { accountId: Number(form.accountId), categoryId: Number(form.categoryId), type: form.type, amount: Number(form.amount), currency: form.currency || 'CNY', description: form.description.trim() || null, transactedAt: toLocalDateTime(form.transactedAt) }; try { if (editingId) { await api.put(`/transactions/${editingId}`, payload); setSuccess('流水已更新'); } else { await api.post('/transactions', payload); setSuccess('流水已创建'); } resetForm(); setShowForm(false); await fetchOptions(); await fetchTransactions(page); } catch (err) { setError(getErrorMessage(err, '操作失败，请稍后重试')); } };
    const edit = (transaction: Transaction) => { setEditingId(transaction.id); setForm({ accountId: String(transaction.accountId), categoryId: String(transaction.categoryId), type: transaction.type, amount: String(transaction.amount), currency: transaction.currency || 'CNY', description: transaction.description || '', transactedAt: toInputDateTime(transaction.transactedAt) }); setShowForm(true); setError(''); setSuccess(''); };
    const remove = async (transaction: Transaction) => { if (!confirm('确定删除这条流水吗？')) return; try { await api.delete(`/transactions/${transaction.id}`); const nextPage = transactions.length === 1 && page > 1 ? page - 1 : page; setSuccess('流水已删除'); setError(''); await fetchOptions(); await fetchTransactions(nextPage); } catch (err) { setError(getErrorMessage(err, '操作失败，请稍后重试')); } };
    const search = async (event: FormEvent) => { event.preventDefault(); setError(''); setSuccess(''); try { await fetchTransactions(1); } catch (err) { setError(getErrorMessage(err, '操作失败，请稍后重试')); } };
    const totalPages = Math.max(1, Math.ceil(total / pageSize)); const goPage = async (nextPage: number) => { if (nextPage < 1 || nextPage > totalPages) return; try { await fetchTransactions(nextPage); } catch (err) { setError(getErrorMessage(err, '操作失败，请稍后重试')); } };
    return <div>
        <PageHeader title="交易流水" subtitle="按账户、分类和时间范围筛选与管理您的交易记录" actions={<button type="button" className="button button--primary" onClick={showForm ? closeForm : openCreateForm}>{showForm ? '收起表单' : '新增流水'}</button>} />
        {error && <AlertMessage type="error">{error}</AlertMessage>}{success && <AlertMessage type="success">{success}</AlertMessage>}
        <form onSubmit={search} className="page-panel page-panel--compact"><div className="filter-grid"><Field label="类型"><select className="field__control" value={filters.type} onChange={event => setFilters({ ...filters, type: event.target.value })}><option value="">全部</option>{typeOptions.map(type => <option key={type} value={type}>{formatTransactionType(type)}</option>)}</select></Field><Field label="账户"><select className="field__control" value={filters.accountId} onChange={event => setFilters({ ...filters, accountId: event.target.value })}><option value="">全部</option>{accounts.map(account => <option key={account.id} value={account.id}>{account.name}</option>)}</select></Field><Field label="分类"><select className="field__control" value={filters.categoryId} onChange={event => setFilters({ ...filters, categoryId: event.target.value })}><option value="">全部</option>{categories.map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select></Field><Field label="开始时间"><input className="field__control" type="datetime-local" value={filters.start} onChange={event => setFilters({ ...filters, start: event.target.value })} /></Field><Field label="结束时间"><input className="field__control" type="datetime-local" value={filters.end} onChange={event => setFilters({ ...filters, end: event.target.value })} /></Field><button type="submit" className="button button--primary">筛选</button></div></form>
        {showForm && <form onSubmit={submit} className="page-panel"><h2 className="content-card__title">{editingId ? '编辑流水' : '新增流水'}</h2><div className="form-grid form-grid--auto"><Field label="类型"><select className="field__control" value={form.type} onChange={event => setForm({ ...form, type: event.target.value as TransactionType, categoryId: '' })}>{typeOptions.map(type => <option key={type} value={type}>{formatTransactionType(type)}</option>)}</select></Field><Field label="账户"><select className="field__control" value={form.accountId} onChange={event => setForm({ ...form, accountId: event.target.value })} required><option value="">请选择账户</option>{accounts.filter(account => account.status === 'ACTIVE').map(account => <option key={account.id} value={account.id}>{account.name}</option>)}</select></Field><Field label="分类"><select className="field__control" value={form.categoryId} onChange={event => setForm({ ...form, categoryId: event.target.value })} required><option value="">请选择分类</option>{selectableCategories.map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select></Field><Field label="金额"><input className="field__control" type="number" step="0.01" value={form.amount} onChange={event => setForm({ ...form, amount: event.target.value })} required /></Field><Field label="币种"><input className="field__control" value={form.currency} onChange={event => setForm({ ...form, currency: event.target.value })} /></Field><Field label="交易时间"><input className="field__control" type="datetime-local" value={form.transactedAt} onChange={event => setForm({ ...form, transactedAt: event.target.value })} required /></Field></div><div style={{ marginTop: 12 }}><Field label="说明"><input className="field__control" value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} placeholder={form.type === 'ADJUSTMENT' ? '调整流水必须填写说明' : '可选'} /></Field></div><div className="data-table__actions" style={{ marginTop: 16 }}><button type="submit" className="button button--primary">{editingId ? '保存修改' : '保存'}</button>{editingId && <button type="button" className="button button--neutral" onClick={closeForm}>取消编辑</button>}</div></form>}
        <section className="content-card"><h2 className="content-card__title"><span className="content-card__title-icon"><Icon name="transactions" size={17} /></span>交易记录</h2><div className="table-scroll"><table className="data-table"><thead><tr><th>时间</th><th>类型</th><th>账户</th><th>分类</th><th className="cell-number">金额</th><th>币种</th><th>说明</th><th>操作</th></tr></thead><tbody>{transactions.map(transaction => <tr key={transaction.id}><td>{transaction.transactedAt?.replace('T', ' ')}</td><td><TransactionBadge type={transaction.type} /></td><td>{accountNameById.get(transaction.accountId) || transaction.accountId}</td><td>{categoryNameById.get(transaction.categoryId) || transaction.categoryId}</td><td className="cell-number"><span className={`amount amount--${transaction.type === 'INCOME' ? 'positive' : transaction.type === 'EXPENSE' ? 'negative' : 'neutral'}`}>{formatTransactionAmount(transaction.type, transaction.amount)}</span></td><td>{transaction.currency}</td><td>{transaction.description || '-'}</td><td className="cell-actions"><div className="data-table__actions"><button type="button" className="button button--secondary button--small" onClick={() => edit(transaction)}>编辑</button><button type="button" className="button button--danger button--small" onClick={() => remove(transaction)}>删除</button></div></td></tr>)}{transactions.length === 0 && <EmptyTableRow colSpan={8} message="暂无流水" />}</tbody></table></div><Pagination page={page} totalPages={totalPages} summary={<>共 {total} 条</>} previousDisabled={page <= 1} nextDisabled={page >= totalPages} onPrevious={() => goPage(page - 1)} onNext={() => goPage(page + 1)} /></section>
    </div>;
}
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="field"><span className="field__label">{label}</span>{children}</label>; }
function TransactionBadge({ type }: { type: TransactionType }) { return <Badge tone={type === 'INCOME' ? 'success' : type === 'EXPENSE' ? 'danger' : 'primary'}>{formatTransactionType(type)}</Badge>; }
