import { useEffect, useRef, useState } from 'react';
import api from '../../api';
import type { InvestmentAccount, InvestmentInstrument, InvestmentPositionDetail, InvestmentTransactionDetail } from '../../types/investment';
import type { InvestmentCommandDraft, InvestmentCommandType } from '../../types/investmentCommand';
import { buildCommandConfirmation } from '../../utils/investmentCommandConfirmation';
import { canOfferBuyWithAuthoritativeEligibility, validateDraft } from '../../utils/investmentCommandValidation';

const emptyDraft = (commandType: InvestmentCommandType, position?: InvestmentPositionDetail, transaction?: InvestmentTransactionDetail, transactionPositionId?: number): InvestmentCommandDraft => ({
    commandType, replacementTransactionType: commandType === 'REPLACEMENT' && transaction?.transactionType !== 'OPENING_POSITION' ? transaction?.transactionType : undefined, replacementRequestType: commandType === 'REPLACEMENT' && transaction?.transactionType !== 'OPENING_POSITION' ? transaction?.transactionType : undefined, assetId: position?.positionId ?? transactionPositionId, logicalTransactionId: transaction?.logicalTransactionId,
    quantity: (transaction?.effectiveBusinessValues ?? transaction?.originalBusinessValues)?.quantity ?? '', unitPrice: (transaction?.effectiveBusinessValues ?? transaction?.originalBusinessValues)?.unitPrice ?? '', grossAmount: (transaction?.effectiveBusinessValues ?? transaction?.originalBusinessValues)?.grossAmount ?? '', feeAmount: (transaction?.effectiveBusinessValues ?? transaction?.originalBusinessValues)?.feeAmount ?? '0.00', taxAmount: (transaction?.effectiveBusinessValues ?? transaction?.originalBusinessValues)?.taxAmount ?? '0.00', externalReference: (transaction?.effectiveBusinessValues ?? transaction?.originalBusinessValues)?.externalReference ?? '', note: (transaction?.effectiveBusinessValues ?? transaction?.originalBusinessValues)?.note ?? '', reason: '',
});

const validationErrorId = 'investment-command-validation-error';

export function InvestmentCommandDialog({ commandType, position, transaction, transactionPositionId, onClose, onSubmit }: { commandType: InvestmentCommandType; position?: InvestmentPositionDetail; transaction?: InvestmentTransactionDetail; transactionPositionId?: number; onClose: () => void; onSubmit: (draft: InvestmentCommandDraft) => Promise<void>; }) {
    const [draft, setDraft] = useState(() => emptyDraft(commandType, position, transaction, transactionPositionId));
    const [confirming, setConfirming] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [firstBuyEligible, setFirstBuyEligible] = useState<boolean | null>(null); const dialogRef = useRef<HTMLElement>(null); const title = commandType === 'FIRST_BUY' ? '记录第一笔投资' : commandType === 'BUY' ? position?.status === 'CLOSED' ? '记录买入并重新打开' : '记录买入' : commandType === 'SELL' ? '记录卖出' : commandType === 'DIVIDEND' ? '记录分红' : commandType === 'REVERSAL' ? '冲正交易' : '更正交易';
    useEffect(() => { const initial = dialogRef.current?.querySelector<HTMLElement>('input, select, textarea, button, [tabindex]:not([tabindex="-1"])'); initial?.focus(); }, []);
    const close = () => { onClose(); };
    const trapFocus = (event: React.KeyboardEvent<HTMLElement>) => {
        if (event.key === 'Escape') { if (!busy) { if (confirming) setConfirming(false); else close(); } return; }
        if (event.key !== 'Tab') return;
        const elements = [...(dialogRef.current?.querySelectorAll<HTMLElement>('a[href], button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])') ?? [])].filter(element => !element.hidden);
        if (elements.length === 0) { event.preventDefault(); return; }
        const first = elements[0]; const last = elements[elements.length - 1];
        if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); }
        else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); }
    };
    const set = <K extends keyof InvestmentCommandDraft>(key: K, value: InvestmentCommandDraft[K]) => setDraft(current => ({ ...current, [key]: value }));
    const review = () => { const validation = validateDraft(draft); if (validation) { setError(validation); return; } if (draft.commandType === 'FIRST_BUY' && firstBuyEligible !== true) { setError('账户或标的当前不可用于记录买入。'); return; } setError(''); setConfirming(true); };
    const submit = async () => { setBusy(true); setError(''); try { await onSubmit(draft); close(); } catch (reason) { const status = (reason as { response?: { status?: number } })?.response?.status; if (status === 409 || status === 401 || !status || status >= 500) close(); else setError(reason instanceof Error ? reason.message : '无法安全提交投资记录。'); } finally { setBusy(false); } };
    return <div className="command-modal-backdrop" role="presentation"><section ref={dialogRef} className="command-modal" role="dialog" aria-modal="true" aria-labelledby="investment-command-title" aria-describedby="investment-command-description" onKeyDown={trapFocus}><header><p className="section-heading__eyebrow">INVESTMENT COMMAND</p><h2 id="investment-command-title">{confirming ? `确认${title}` : title}</h2></header><p id="investment-command-description" className="sr-only">投资命令对话框。提交期间不可关闭，所有金额以字符串提交并由后端计算最终账本结果。</p>{error && <p id={validationErrorId} className="alert alert--error" role="alert" tabIndex={-1}>{error}</p>}
        {confirming ? <Confirmation draft={draft} position={position} transaction={transaction} /> : <CommandForm draft={draft} position={position} transaction={transaction} error={error} set={set} onFirstBuyEligibilityChange={setFirstBuyEligible} />}
        <footer className="command-modal__actions">{confirming ? <><button type="button" className="button button--secondary" disabled={busy} onClick={() => setConfirming(false)}>返回编辑</button><button type="button" className="button button--primary" disabled={busy} onClick={() => void submit()}>{busy ? '正在安全提交…' : commandType === 'REVERSAL' ? '确认冲正' : commandType === 'REPLACEMENT' ? '确认更正' : '确认记录'}</button></> : <><button type="button" className="button button--secondary" disabled={busy} onClick={close}>取消</button><button type="button" className="button button--primary" disabled={commandType === 'FIRST_BUY' && firstBuyEligible !== true} onClick={review}>进入复核</button></>}</footer>
    </section></div>;
}

function CommandForm({ draft, position, transaction, error, set, onFirstBuyEligibilityChange }: { draft: InvestmentCommandDraft; position?: InvestmentPositionDetail; transaction?: InvestmentTransactionDetail; error: string; set: <K extends keyof InvestmentCommandDraft>(key: K, value: InvestmentCommandDraft[K]) => void; onFirstBuyEligibilityChange: (eligible: boolean | null) => void; }) {
    const trade = draft.commandType === 'FIRST_BUY' || draft.commandType === 'BUY' || draft.commandType === 'SELL' || draft.commandType === 'REPLACEMENT' && transaction?.transactionType !== 'DIVIDEND';
    if (draft.commandType === 'REVERSAL') return <><p>冲正会追加不可变纠正事实，不会删除原始交易；原始记录仍保留在审计时间线中。</p><Text label="纠正原因" value={draft.reason} error={error} onChange={value => set('reason', value)} /></>;
    return <div className="command-form">{draft.commandType === 'FIRST_BUY' && <FirstBuyPrerequisites draft={draft} set={set} onEligibilityChange={onFirstBuyEligibilityChange} />}{position && <p className="investment-detail__note">目标持仓：{position.instrument.name}（{position.instrument.symbol}） · {position.account.displayName}</p>}{transaction && <p className="investment-detail__note">原始交易：{transaction.transactionType} · {transaction.instrument.name}（{transaction.instrument.symbol}）</p>}
        {trade ? <><Text label="数量" value={draft.quantity} error={error} onChange={value => set('quantity', value)} /><Text label="单价" value={draft.unitPrice} error={error} onChange={value => set('unitPrice', value)} /></> : <Text label="分红总额" value={draft.grossAmount} error={error} onChange={value => set('grossAmount', value)} />}
        <Text label="费用" value={draft.feeAmount} error={error} onChange={value => set('feeAmount', value)} /><Text label="税费" value={draft.taxAmount} error={error} onChange={value => set('taxAmount', value)} />
        {draft.commandType !== 'FIRST_BUY' && draft.commandType !== 'BUY' && draft.commandType !== 'SELL' && <><Text label="外部参考号（可选）" value={draft.externalReference} error={error} onChange={value => set('externalReference', value)} /><Text label="备注（可选）" value={draft.note} error={error} onChange={value => set('note', value)} /></>}
        {draft.commandType === 'REPLACEMENT' && <Text label="更正原因" value={draft.reason} error={error} onChange={value => set('reason', value)} />}{draft.commandType === 'SELL' && <p className="investment-detail__note">最终释放成本、已实现盈亏、余额和持仓由后端计算。</p>}{draft.commandType === 'DIVIDEND' && <p className="investment-detail__note">数量、成本与持仓状态由后端保持权威。</p>}
    </div>;
}
function FirstBuyPrerequisites({ draft, set, onEligibilityChange }: { draft: InvestmentCommandDraft; set: <K extends keyof InvestmentCommandDraft>(key: K, value: InvestmentCommandDraft[K]) => void; onEligibilityChange: (eligible: boolean | null) => void; }) {
    const [accounts, setAccounts] = useState<InvestmentAccount[]>([]); const [instruments, setInstruments] = useState<InvestmentInstrument[]>([]); const [creating, setCreating] = useState(false); const [instrument, setInstrument] = useState({ symbol: '', name: '', market: '', assetClass: 'STOCK', quoteCurrency: 'CNY' });
    useEffect(() => { void api.get('/accounts/page', { params: { page: 1, size: 100 } }).then(response => setAccounts((response.data.data.records ?? []).map((account: { id: number; name: string; type?: string; status?: string; currency?: string }) => ({ id: account.id, displayName: account.name, type: account.type, status: account.status, currency: account.currency })))); void api.get('/investment/instruments').then(response => setInstruments(response.data.data as InvestmentInstrument[])); }, []);
    const account = accounts.find(item => item.id === draft.accountId);
    const instrumentItem = instruments.find(item => item.id === draft.instrumentId);
    const eligible = account && instrumentItem ? canOfferBuyWithAuthoritativeEligibility(account.status, account.type, instrumentItem.status, instrumentItem.assetClass) : false;
    useEffect(() => { onEligibilityChange(account && instrumentItem ? eligible : null); }, [account, eligible, instrumentItem, onEligibilityChange]);
    const create = async () => { const response = await api.post('/investment/instruments', instrument); const created = response.data.data as InvestmentInstrument; setInstruments(current => [...current, created]); set('instrumentId', created.id); setCreating(false); };
    return <><label className="field"><span className="field__label">账户</span><select className="field__control" value={draft.accountId ?? ''} onChange={event => set('accountId', Number(event.target.value) || undefined)} required><option value="">选择账户</option>{accounts.map(account => <option key={account.id} value={account.id}>{account.displayName}</option>)}</select></label><label className="field"><span className="field__label">投资标的</span><select className="field__control" value={draft.instrumentId ?? ''} onChange={event => set('instrumentId', Number(event.target.value) || undefined)} required><option value="">选择标的</option>{instruments.map(item => <option key={item.id} value={item.id}>{item.symbol} · {item.name} · {item.market}</option>)}</select></label>{account && instrumentItem && !eligible && <p className="alert alert--error" role="alert">账户或标的当前不可用于记录买入。</p>}<button type="button" className="button button--secondary button--small" onClick={() => setCreating(value => !value)}>新建投资标的</button>{creating && <div className="form-grid"><Text label="代码" value={instrument.symbol} onChange={symbol => setInstrument(current => ({ ...current, symbol }))} /><Text label="名称" value={instrument.name} onChange={name => setInstrument(current => ({ ...current, name }))} /><Text label="市场" value={instrument.market} onChange={market => setInstrument(current => ({ ...current, market }))} /><Text label="资产类别" value={instrument.assetClass} onChange={assetClass => setInstrument(current => ({ ...current, assetClass }))} /><Text label="报价货币" value={instrument.quoteCurrency} onChange={quoteCurrency => setInstrument(current => ({ ...current, quoteCurrency }))} /><button type="button" className="button button--secondary" onClick={() => void create()}>创建并选择</button></div>}</>;
}
function Confirmation({ draft, position, transaction }: { draft: InvestmentCommandDraft; position?: InvestmentPositionDetail; transaction?: InvestmentTransactionDetail }) {
    const model = buildCommandConfirmation(draft, position ? { instrumentName: position.instrument.name, instrumentSymbol: position.instrument.symbol, accountName: position.account.displayName, currentQuantity: position.quantity } : undefined, transaction ? { instrumentName: transaction.instrument.name, instrumentSymbol: transaction.instrument.symbol, accountName: transaction.account.displayName, transactionType: transaction.transactionType, effectiveTradeTime: transaction.effectiveTradeTime, original: transaction.originalBusinessValues } : undefined);
    return <div className="command-confirmation"><p>{model.notice}</p><dl>{model.rows.map(([label, value]) => <span key={label}><dt>{label}</dt><dd>{value}</dd></span>)}</dl>{model.comparisons && <div className="table-scroll"><table className="data-table"><thead><tr><th scope="col">字段</th><th scope="col">原记录</th><th scope="col">更正后</th></tr></thead><tbody>{model.comparisons.map(([label, before, after]) => <tr key={label}><th scope="row">{label}</th><td>{before}</td><td>{after}</td></tr>)}</tbody></table></div>}</div>;
}
function Text({ label, value, error, onChange }: { label: string; value: string; error?: string; onChange: (value: string) => void }) { const invalid = Boolean(error?.startsWith(label)); return <label className="field"><span className="field__label">{label}</span><input className="field__control" value={value} aria-describedby={invalid ? validationErrorId : undefined} aria-invalid={invalid || undefined} onChange={event => onChange(event.target.value)} /></label>; }
